USE   MOVIES;
CREATE TABLE ACTOR (
Act_Id    integer  NOT NULL,
Act_fname  CHAR(45) NOT NULL,
Act_lname  CHAR(20)   NOT NULL,
Act_gender  CHAR(1)   NOT NULL,
CONSTRAINT    Actor_pk  PRIMARY KEY(act_id));

CREATE TABLE DIRECTOR(
DIR_ID   INTEGER  NOT NULL,
DIR_FNAME  CHAR(20) NOT NULL,
DIR_LNAME   CHAR(20) NOT NULL,
CONSTRAINT   DIRECTOR_PK    PRIMARY KEY(DIR_ID));

CREATE TABLE  MOVIE(
MOV_ID   INTEGER  NOT NULL,
MOV_TITLE  CHAR(50) NOT NULL,
MOV_YEAR   INTEGER   NOT NULL,
MOV_TIME   INTEGER   NOT NULL,
MOV_LANG    CHAR(50)  NOT NULL,
MOV_DT_REL   DATE     NOT NULL,
MOV_REL_COUNTRY  CHAR(50) NOT NULL,
CONSTRAINT  MOV_ID   primary key(mov_id));


 CREATE  TABLE  MOVIE_DIRECTION (
 DIR_ID  INTEGER  NOT NULL,
 MOV_ID   INTEGER  NOT NULL,
 FOREIGN KEY (DIR_ID)  REFERENCES DIRECTOR(DIR_ID),
 FOREIGN  KEY (MOV_ID)  REFERENCES  MOVIE(MOV_ID));human
 
 CREATE TABLE MOVIE_CAST(
 ACT_ID   INTEGER NOT NULL,
 MOV_ID  INTEGER NOT NULL,
 ROLE   CHAR(30)   NOT NULL, 
FOREIGN KEY (ACT_ID)  REFERENCES ACTOR( ACT_ID),
FOREIGN KEY ( MOV_ID)  REFERENCES MOVIE( MOV_ID));

CREATE TABLE REVIEWER (
REV_ID  INTEGER NOT NULL,
REV_NAME  CHAR(30) NOT NULL,
CONSTRAINT  REV_ID  PRIMARY KEY(REV_ID));

CREATE TABLE GENRES (
GEN_ID INTEGER NOT NULL,
GEN_TITLE  CHAR(20) NOT NULL,
CONSTRAINT   GEN_ID   PRIMARY KEY(GEN_ID));

CREATE  TABLE  MOVIE_GENRES (
MOV_ID  INTEGER NOT NULL,
GEN_ID INTEGER NOT NULL,
FOREIGN KEY (MOV_ID) REFERENCES MOVIE(MOV_ID),
FOREIGN KEY (GEN_ID) REFERENCES GENRES(GEN_ID));

CREATE TABLE RATING (
MOV_ID INTEGER NOT NULL,
REV_ID  INTEGER NOT NULL,
REV_STARS  INTEGER NOT NULL,
NUM_O_RATINGS INTEGER NOT NULL,
FOREIGN KEY (MOV_ID) REFERENCES MOVIE(MOV_ID),
FOREIGN KEY (REV_ID) REFERENCES  REVIEWER(REV_ID));




